const QOTD = [
  "What do you know how to do that's useless?",
  "What's something in your fridge right now that should probably be thrown out?",
  'How do you best like your ice-cream?',
  'What do you try to do to make the world a little better?',
  'What do you see happening in your future?',
  "What would someone who doesn't know you well be most surprised about?",
  "What's something that was completely out-of-character that you did?",
  'What app or website completely changed your life?',
  "Of all the things you've bought in your life, What has been the worst purchase?",
  'What do you think would be the worst thing about being famous?',
  'What food do you have a love-hate relationship with?',
  "What's your favorite room in your house and why?",
  "What's your current biggest worry?",
  "What's your most recent passion?",
  "What's something others purchase that you simply can't understand why?",
  "What's the best comeback you've ever heard?",
  "Where is the last place you've been where you felt completely out of place?",
  'What question do you have that nobody has been able to give you a good answer to?',
  "What's the worst piece of advice you ever got from someone?",
  'What was the best thing you learned in the past year?',
  'Do you, or did you in the past, have any strange habits?',
  'Are you currently going through any type of phase?',
  'What is something that you find mildly annoying, but not annoying enough to do anything about?',
  "What is something you predict will exist in 10 years that doesn't today?",
  'What is something you thought would be a great idea but was terrible when you actually did it?',
  'What do you wish you had more talent doing?',
  'Can you describe your personal style?',
  'Have you ever done something embarrassing around a former crush?',
  "What do you like to do that's traditionally considered masculine?",
  'Can you explain love?',
  "What's the biggest wager you've ever made?",
  'What is your opinion on social media?',
  'What bad decision did you make that actually turned out to be a good decision?',
  "What's something you find attractive that others may not?",
  'What was your most recent experience of going down the rabbit hole?',
  "What's something that is common today that humans will be embarrassed about doing in 50 years?",
  'What do you know is bad for you but you continue to do it anyway?',
  'What is your current go-to song to dance to when nobody is around?',
  "What's your favorite ritual?",
  'What type of exercise do you like most?',
  'What line from a song has had the biggest impact on you?',
  "What's the most interesting conversation you eavesdropped on?",
  "What's something that you know that few other people know?",
  "What small stuff do you sweat even though you know you shouldn't?",
  "What's an example of when you changed your mind?",
  'Do you consider yourself an introvert or an extrovert?',
  'What future year are you most looking forward to arriving?',
  'If you had to wear a hat for the next week, What type of hat would you choose?',
  "What's the most interesting thing you have in your pockets right now?",
  'If you had the choice to go back in time or into the future, which would you choose?',
  "What is the next big purchase you're currently saving for?",
  'If you could have any person become a member of your family, who would you choose?',
  'What little thing instantly tells you that a person is good?',
  "What's something that you recently learned that everyone else already knew?",
  'What book or movie character can you see in your own life?',
  'What thing have you been procrastinating about that you will begin doing today?',
  'What do you find extremely difficult that most people find simple?',
  "Who is someone you recently thought about that you haven't seen or talked to in years?",
  'On any given day, What do you think you spend the most time doing?',
  'Without saying the category, What are your top five?',
  'What did you recently learn the hard way?',
  "What is the funniest false thing you were able to convince others that's true?",
  'How would a random stranger describe you?, How accurate would that be?',
  "What do you do in secret that you're proud of?",
  'If you were to work at a circus, What job would you choose?',
  'What do you spend too much time doing?',
  'What was the last thing that truly disappointed you?',
  'What is something that you learned from simply watching a stranger?',
  'Who have you met only one time that left a huge impression on you?',
  'Do you enjoy people watching?',
  'What is the last big argument you go into and who was it with?',
  'If you could play a prank on any historical figure, who would you pick and What prank would you do?',
  "What's the best way you've found to calm yourself when you get stressed?",
  'What is the quickest way for you to lose respect for someone?',
  'Have you ever let someone else get punished for something you did?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  "What's the most amount of money you've ever found?",
  'What was the situation?',
  'What weird thing do you do when nobody else is around?',
  'What topic can you bring up at a family gathering to instantly get everyone riled up?',
  "What's the best part of rain?",
  'What have you recently found to be ironic?',
  'How would you describe someone who is wealthy?',
  'If everyone here was a color, What color would each person be?',
  'Is there any place that you have no desire to visit?, Why?',
  'What have you been thinking about lately that has kept you up at night?',
  "What's something that you believe that most other people don't?",
  'What have you recently felt grateful for?',
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  'If you were to be famous for something, What would that be?',
  "What's something that you know you should start, but haven't?",
  "What part of your body currently doesn't feel 100%?",
  "Do you have any apps on your phone that you've never used?",
  'Without saying the category, what are your top five?',
  'What is your current favorite TV show? What was it 5 years ago?',
  'What sound will instantly melt your heart?',
  'How difficult is it for you to try new things?',
  'If you were to devote your life to art, what type of art would that be?',
  'What technology advance are you looking forward to in the future?',
  "What is something that happened to you that you can't logically explain?",
  'If you had to pick a single word to describe this year so far, what would it be?',
  'What is something that you would really like to try again?',
  "What is the best random act of kindness you've ever witnessed?",
  'Have you ever had a terrible house guest? If so, what happened?',
  'If you could assign one household chore to someone else, what would it be?',
  "What's something that you believe you'll never be able to do well?",
  'What do you think is the most complex aspect about yourself?',
  'What mode of transportation have you never tried?',
  'When was the last memorable sunrise you witnessed?',
  "What do you like to do that's considered touristy?",
  'What do you think is the most valuable resource?',
  "What's something about you today that the old you would find surprising?",
  'What do you consider the most difficult food to eat?',
  'What has been your 15 minutes of fame up to this point?',
  'What do you think is the most useful skill to know?',
  "What's your opinion on tipping?",
  "What's the most difficult thing about being you?",
  'How do you make decisions?',
  'What would be the best thing about losing your hearing?',
  'What part of the human face do you look at when you talk to someone?',
  'What piece of art has had a large impact on you?',
  'At what age did you think you become an adult and when do you actually think you did?',
  'What argument did you have that looking back on was absolutely ridiculous?',
  "What's the story about the last time you cried?",
  "What would you be really good at if it wasn't for one thing?",
  'What is money to you?',
  'Do you have a dream job in mind?, What would it be?',
  'On any given day, what do you think you spend the most time doing?',
  "What's the story behind your greatest treasure?",
  "What's an interesting fact that you recently learned?",
  "What's the one thing that you seem to constantly lose?",
  'What is it that motivates yourself the most?',
  'What are the top three qualities you admire in others?',
  'What the best thing that can happen in the first 5 minutes after waking up?',
  "What's your opinion on cell phones?",
  'What would be the best and worst part of being a cat in your opinion?',
  "What are some things don't you understand about the opposite sex?",
  'Is time currently passing quickly or slowly for you?',
  'Do you have a bucket list?',
  'How long did it take for you to come up with your current signature?',
  "What's the next line to cross off your list?",
  "What is something that you don't mind waiting for?",
  'Have you ever had to complain to management? Why?',
  "What's the last thing that you broke and how did it happen?",
  'Did you ever have a huge rival? Was the rivalry friendly or fierce?',
  'What do you love most about where you grew up?',
  'How much money would you need in the bank to feel comfortable to retire today?',
  "What's the strangest situation you ever found yourself in?",
  'What is something you feel is unacceptable that is still being done today?',
  'What were you most afraid of when you were younger? Do you still have that fear?',
  'What do you find is the most boring part of your life at the moment?',
  'Do you believe that money can make you happy?',
  'How do you usually react if you receive bad service?',
  'If you knew the winning lottery numbers, would you keep them to yourself or share with others?',
  "What do you think people pretend to like when they really don't?",
  'Do you have a nightmare travel story?',
  "What's the story behind your favorite memento?",
  'What are the top three characteristics you feel are important for a person?',
  "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
  'When are you most productive?',
  'Have you ever had or witnessed a drop the mic moment?',
  'How would you spend $1,000 to give the most happiness to the most number of people possible?',
  'In emergency situations, how do you react?',
  'If you were handed $500 at this moment, how would you spend it?',
  "What is the most selfish thing you do that you're okay with?",
  'What is the last encounter you had with a random stranger?',
  'What was the last dream you can remember about?',
  'What old school skill set do you have?',
  'What is something you own that you have never used?',
  "Who in your family can't you believe you're related to?",
  "What's your opinion on social media?",
  'What can you talk about for hours?',
  "What's something that you use regularly that you wish you didn't have to?",
  'Do you people watch? If so, where do you like to do this most?',
  "What's the story behind your last rant?",
  'What is your biggest regret from the last month?',
  'What obscure interest do you have?',
  'How do you approach life?',
  'What uncommon thing would you encourage everyone to try once?',
  "What is the most recent life lesson you've learned?",
  'What destination is at the top of your list to visit?',
  'Would you consider yourself decisive or indecisive?',
  'Do you think you were ever part of the popular crowd?',
  "If it's raining outside, what activity do you most want to do?",
  "What's the last thing you complained about?",
  'What or who are you always willing to make time for?',
  'What recent experience made you feel old?',
  "What's your biggest first world problem?",
  'If you could only buy ten items at the grocery store to last the next week, what would you buy?',
  'Do you have any unusual fears?',
  'What do you hope to be an expert about at some point in your life?',
  'What are your favorite five words at the moment?',
  'Who was the last person you made happy and what did you do to do it?',
  'What recent situation was nearly a disaster, but you were able to prevent it?',
  'What law have you broken the most in your life?',
  'Do you have any secret hobbies?',
  "What's something that really happened to you but nobody would believe unless they were there?",
  "What's the worst accident you ever had?",
  'If you had to choose, would you rather be too hot or too cold?',
  'What is your opinion on tattoos?',
  'What song do you secretly sing in the shower?',
  'What situation is sure to make you cry?',
  "What's the embarrassing story that your parents used to tell others about you?",
  "What's your opinion on naps?",
  "What's the most recent interesting conversation you had?",
  'How would you describe your sense of humor? Can you give an example?',
  "What's your story about being under intense pressure and how did you handle it?",
  'Are you a planner or more of a go with whatever happens when it comes to travel?',
  'Do you have a secret place?',
  'If you had to name one thing that makes you stand out from others, what would that be?',
  'Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?',
  'Where was your secret hiding place as a child?',
  'Would the world be better or worse if superheroes existed?',
  'If you had to change the language you speak, which one would you choose?',
  "What's the last goal you set for yourself that you accomplished?",
  'If you were to work at a circus, what job would you choose?',
  "Can you name 5 things you wouldn't do for a million dollars?",
  'Do you consider telling white lies to be okay?',
  'What do you remember most about your first crush?',
  'What food combination do you eat that makes others cringe?',
  'What assumption have you made that ended up being completely incorrect?',
  'How long does it take you to form an opinion about a person?',
  "What's something that when you were learning it, you thought you'd never use it, but in reality, you ended up using it a lot?",
  'When you want to escape from everyone, where do you go?',
  "What's something interesting about you that few people know?",
  'What have you found more helpful than you ever imagined it could be?',
  "Is there a personality trait that you'd like to adopt from one of your friends?",
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  "What is the next skill that you'd like to learn really well?",
  "What's a situation when you look back you should have gone ahead and done it?",
  'Have you taken a long shot that worked out?',
  "What is the messiest situation you've ever encountered?",
  "What's your current Golden Rule when it comes to living life?",
  "What's the best trick someone has ever played on you?",
  'What question have people recently been constantly asking you?',
  "What's most important to you about your school/work environment?",
  'Have you ever been at an event that you think will one day be in history books?',
  "What's the most spontaneous thing you've ever done?",
  'What would your dream day look like?',
  'What part of history do you find most interesting?',
  'What was the last meltdown that you witnessed?',
  "What's your favorite thing to do when you're all alone?",
  'What is your best shower thought?',
  'Are you currently where you want to be in life?',
  'Do you believe there is only one other person in the world for you or many?',
  'What is something that someone does that will immediately turn you off?',
  'Where is the strangest place you have fallen asleep?',
  'If you could only ask one question to each person you meet, what would that question be?',
  'What would you do if you saw a giraffe on the side of the road?',
  "What was a past passion that you can't believe you were so passionate about?",
  'What song currently speaks to you the most?',
  'Do you have a dream job in mind? What would it be?',
  "What is the most interesting class you've ever taken?",
  "What's one thing you think you should be doing more often?",
  'What is the easiest way to bring a smile to your face?',
  "What's the best compliment you ever received?",
  "What's something that you thought you'd have already done by now, but haven't?",
  'If you were going to start your own business, what would it be?',
  "Do you think you're more like your mom or your dad?",
  'Is there anything that most people find cute that creeps you out?',
  'What is a restaurant you refuse to eat at and why?',
  'What is something that you absolutely will not put up with?',
  "What's your close call story?",
  'What country sounds interesting but you know very little about it?',
  'Do you have a favorite brand?',
  "What's something that you completely don't understand?",
  'What is the strangest way you met one of your friends?',
  'What are your top five snacks?',
  'What uncommon thing would you like to see become more common?',
  "What's some small thing you recently noticed?",
  'What was the unspoken scandal in your town when growing up?',
  'If you knew you could live forever, how would you spend your days differently?',
  "What's your definition of success? Has it changed over time?",
  'What is something immature you think your parents do?',
  "What is the assumption that people make about you that's totally wrong?",
  "What will be your go-to story when you're old?",
  "What's something that you think you may have been the only person in the world to ever do?",
  'Have you been given any good advice lately?',
  'What do you find you recently spend a lot of time wondering about?',
  'If you had to ask yourself one question to get the most information out of you, what would that question be?',
  'Do you have a reoccurring dream?',
  "Who is someone you need to contact that you haven't?",
  "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
  'What is the next thing you have on your to-buy list?',
  "What's the most difficult thing that you still do each day?",
  'If you had to describe your current life as a movie, which movie would you choose?',
  "What doesn't exist, but should?",
  'What is your current philosophy about money?',
  'Do you have an app on your phone that you use even though you hate it?',
  "What's the last thing you did alone and you enjoyed?",
  'What activity do you do where your mind wanders in thoughts the most?',
  'How well do you think you understand yourself?',
  'If each person had a warning label, what would yours say?',
  'If you could play a prank on any historical figure, who would you pick and what prank would you do?',
  'How often do you find yourself daydreaming?',
  'What is your favorite spice?',
  "What's your 'famous person' story?",
  'How long do you think you could survive on your own?',
  'If you could lock someone up and throw away the key, would you and if so, who would that be?',
  'Why?',
  "What's your good luck charm?",
  'What challenge would you like to see your best friend take on?',
  'If you had to walk away from one technology in your life, what would it be?',
  "What's a food you vow never to eat?",
  "What's something that you would be willing to stay up all night to do?",
  "What's your plan for surviving a zombie invasion?",
  "What's the most difficult choice you were asked to make?",
  'How do you think your reality differs from others you know?',
  'If you had to wear a hat for the next week, what type of hat would you choose?',
  'Does your family have any weird traditions?',
  "What was your last 'ah-ha' moment?",
  'If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?',
  "What's your go-to funny story now, but was horrendous at that moment?",
  'If you were to be famous for something, what would that be?',
  'What types of things do you doodle?',
  'How well do you trust your gut feelings?',
  'Do you remember what the first school report you wrote was about?',
  "Have you ever been punished for something you didn't do?",
  'Where do you draw the line?',
  "What's something that you never seem to get tired of doing?",
  'Do you have something special that picks you up when you feel down? What is it?',
  'How much damage could your best friend do to you if you ever had a falling out?',
  'How would a random stranger describe you? How accurate would that be?',
  'What food have you never tried?',
  'Of all the problems in the world, which one would you like to see solved first?',
  'Do you name inanimate objects?',
  "What do you wish they would teach at school that they don't?",
  'What are you currently juggling in your life?',
  "When you're by yourself, what do you usually think about?",
]
